# Generated by Django 4.0.2 on 2022-03-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
